# fly.toml app configuration file generated for ai-art-gallery on 2023-10-09T17:58:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-art-gallery"
primary_region = "lhr"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
